### ISSUE TITLE
dry run / mocked run?

### ISSUE THREAD

**Issue by RRMoelker** [xebia/VisualReview-protractor#12]
In a project we are currently piggybacking VisualReview screenshot creation on existing protractor tests. But we also need the flexibility to run these tests without creating screenshots.

Currently each VR call is wrapped in a conditional such as:

```
if (doVR) {
  vr.createScreenshot(...)
}
```

Which works, but is a bit clunky. Another approach is to mock all VR calls in our project. I can image however that this feature is desired by others. So what do you think of having a dryRun / mock / disable option inside the VR protractor project?

I'm leaning to two sub solutions.
1. Immediately exit all VR calls in the first few lines, e.g.: `createRun(...) { if(dryRun) return; )`.
2. Mock all calls to the server, so in `vr-client.js`:

```
createRun (projectName, suiteName) {
  if(doMock) {
     return q.resolve({ ... });
  }
  return _callServer('post', 'runs', {
    ...
  })
```

So do we want the protractor project to have a dryRun feature and if so on what level should we implement it?

**Comment by skwakman** [comment]
hmm interesting idea. The implementation really depends on what you wish to do with the screenshots created by the dry run. 

I'm assuming just reviewing the screenshots without any comparisons or baseline, just to see if the protractor test works correctly? If that's sufficient, here's some thoughts on its implementation:

Currently visualreview allows uploading screenshots against a `run`, which is attached to a `suite` and `project`. We might implement a new type of `run` which is not attached to anything and lacks a baseline, but can simply be used to send screenshots to and easily discard them later. 

Because this type of `run` is not attached no anything, it cannot create comparisons/diffs against another run automatically. We might include this later as an option in the GUI. The process could look like this:
1. `visualreview-protractor`: create a `dry run`, system retrurns an id
2. `visualreview-protractor`: upload screenshots to this `dry run`'s id. 
3. manually review screenshots of this run, without any comparison to anything. This also excludes any 'accept/reject' functionality
4. (optional future enhancement) click some buttons in the review GUI to compare the screenshots with another run. Still no accept/reject functionality though as there's no logical place to keep the baseline.

Implementation wise this would mean that `visualreview-protractor` could introduce a `dry run` configuration parameter. Additionally, `visualreview-server` whould need a new API and gui for creating and reviewing runs that are not attached to a baseline.

What do you think?

**Comment by RRMoelker** [comment]
Haven't look at it like that yet. I'm looking for a simple way to disable screenshots being created for a certain protractor executions. So depending on whether "dryRun" or "disabled" is passed as a configuration parameters the following line produces a screenshot:

```
vr.createScreenshot(...)
```

That is just so we do not need to wrap each VR call ourselves like:

```
if (doVR) {
  vr.createScreenshot(...)
}
```

A simple disable would suffice here. Your solution is a lot more complex than simply having a disable button. I don't think this small of a use case justifies that much complexity.

**Comment by skwakman** [comment]
ah I misread that. I agree, a simple `disabled: true` flag should suffice for the use case you're describing. It might be part of the VisualReview constructor's options, eg:

``` javascript
new VisualReview({
  hostname: 'localhost',
  port: 7000,
  disabled: true
});
```
